C:/Users/user/source/repos/Hoermirzu/ListenToMe-master-89f0b49594deaade7bfad24dad062ff16eca36da/Doxygen_docs/ListenApp/html/search/search.js File Reference
Functions
function convertToId (search)
function getXPos (item)
function getYPos (item)
function SearchBox (name, resultsPath, inFrame, label)
function SearchResults (name)
function setKeyActions (elem, action)
function setClassAttr (elem, attr)
function createResults ()
function init_search ()
Function Documentation
function convertToId (search)
References c.
Referenced by SearchResults().
function createResults ()
References c, searchData, setClassAttr(), and setKeyActions().
function getXPos (item)
Referenced by SearchBox().
function getYPos (item)
Referenced by SearchBox().
function init_search ()
References indexSectionLabels, and key.
function SearchBox (name, resultsPath, inFrame, label)
References getXPos(), getYPos(), if(), indexSectionNames, indexSectionsWithContent, and setTimeout().
function SearchResults (name)
References convertToId(), and if().
function setClassAttr (elem, attr)
Referenced by createResults().
function setKeyActions (elem, action)
Referenced by createResults().