C:/Users/user/source/repos/Hoermirzu/ListenToMe-master-89f0b49594deaade7bfad24dad062ff16eca36da/packages/PhantomJS.2.1.1/tools/phantomjs/examples/page_events.js File Reference
Functions
if (sys.args.length > 1 &&sys.args[1]===`-v`)
function printArgs ()
if (logResources===true)
setTimeout (function(){console.log(``);console.log(`### STEP 1: Load '`+step1url+`'`);page.open(step1url);}, 0)
Variables
use strict
var sys = require(`system`)
var page = require(`webpage`).create()
var logResources = false
var step1url = `http://en.wikipedia.org/wiki/DOM_events`
var step2url = `http://en.wikipedia.org/wiki/DOM_events#Event_flow`
page onInitialized
page onLoadStarted
page onLoadFinished
page onUrlChanged
page onNavigationRequested
page onRepaintRequested
page onClosing
page onConsoleMessage
page onAlert
page onConfirm
page onPrompt
Function Documentation
if (sys.args. length, 1 &&sys. args[1] = == `-v`)
References logResources.
if (logResources = == true)
References page, and printArgs().
function printArgs ()
Referenced by if().
setTimeout (function(){console.log(``);console.log(`### STEP 1: Load '`+step1url+`'`);page.open(step1url);} , 0)
Referenced by SearchBox(), and sleepSort().
Variable Documentation
var logResources = false
Referenced by if().
page onAlert
Initial value:
= function() {
    console.log("page.onAlert");
    printArgs.apply(this, arguments);
}
page onClosing
Initial value:
= function() {
    console.log("page.onClosing");
    printArgs.apply(this, arguments);
}
page onConfirm
Initial value:
= function() {
    console.log("page.onConfirm");
    printArgs.apply(this, arguments);
}
page onConsoleMessage
Initial value:
= function() {
    console.log("page.onConsoleMessage");
    printArgs.apply(this, arguments);
}
page onInitialized
Initial value:
= function() {
    console.log("page.onInitialized");
    printArgs.apply(this, arguments);
}
page onLoadFinished
Initial value:
= function() {
    console.log("page.onLoadFinished");
    printArgs.apply(this, arguments);
}
page onLoadStarted
Initial value:
= function() {
    console.log("page.onLoadStarted");
    printArgs.apply(this, arguments);
}
page onNavigationRequested
Initial value:
= function() {
    console.log("page.onNavigationRequested");
    printArgs.apply(this, arguments);
}
page onPrompt
Initial value:
= function() {
    console.log("page.onPrompt");
    printArgs.apply(this, arguments);
}
page onRepaintRequested
Initial value:
= function() {
    console.log("page.onRepaintRequested");
    printArgs.apply(this, arguments);
}
page onUrlChanged
Initial value:
= function() {
    console.log("page.onUrlChanged");
    printArgs.apply(this, arguments);
}
var page = require(`webpage`).create()
Referenced by if().
var step1url = `http://en.wikipedia.org/wiki/DOM_events`
var step2url = `http://en.wikipedia.org/wiki/DOM_events#Event_flow`
use strict
var sys = require(`system`)