C:/Users/user/source/repos/Hoermirzu/ListenToMe-master-89f0b49594deaade7bfad24dad062ff16eca36da/packages/PhantomJS.2.1.1/tools/phantomjs/examples/responsive-screenshot.js File Reference
Functions
if (1===args.length)
page open (urlAddress, function(status){if('success'!==status){console.log('Unable to load the url address!');}else{var folder=urlToDir(urlAddress);var output, key;function render(n){if(!!n){key=n-1;page.viewportSize=viewports[key];if(clipping){page.clipRect=viewports[key];}output=folder+`/`+getFileName(viewports[key]);console.log('Saving '+output);page.render(output);render(key);}}render(viewports.length);}phantom.exit();})
function getFileName (viewport)
function getFileExtension ()
function getClipping ()
function urlToDir (url)
Variables
var args = require('system').args
var fs = require('fs')
var page = new WebPage()
var urlAddress = args[1].toLowerCase()
var ext = getFileExtension()
var clipping = getClipping()
var viewports
Function Documentation
function getClipping ()
check if clipping
Returns
{boolean}
References args.
function getFileExtension ()
output extension format helper
Returns
{*}
References args.
function getFileName (viewport)
filename generator helper
Parameters
viewport
Returns
{string}
References ext.
if (1 = == args.length)
if url address does not exist, exit phantom
[open(urlAddress, function(status){if('success'!==status){console.log('Unable to load the url address!');}else{var folder=urlToDir(urlAddress);var output, key;function render(n){if(!!n){key=n-1;page.viewportSize=viewports[key];if(clipping){page.clipRect=viewports[key];}output=folder+"/"+getFileName(viewports[key]);console.log('Saving '+output);page.render(output);render(key);}}render(viewports.length);}phantom.exit();})]page open (urlAddress , [function(status){if('success'!==status){console.log('Unable to load the url address!');}else{var folder=urlToDir(urlAddress);var output, key;function render(n){if(!!n){key=n-1;page.viewportSize=viewports[key];if(clipping){page.clipRect=viewports[key];}output=folder+`/`+getFileName(viewports[key]);console.log('Saving '+output);page.render(output);render(key);}}render(viewports.length);}phantom.exit();}])
function urlToDir (url)
url to directory helper
Parameters
url
Returns
{string}
References fs, and url.
Variable Documentation
var args = require('system').args
Captures the full height document even if it's not showing on the screen or captures with the provided range of screen sizes.
A basic example for taking a screen shot using phantomjs which is sampled for https://nodejs-dersleri.github.io/
usage : phantomjs responsive-screenshot.js {url} [output format] [doClipping]
examples > phantomjs responsive-screenshot.js https://nodejs-dersleri.github.io/ phantomjs responsive-screenshot.js https://nodejs-dersleri.github.io/ pdf phantomjs responsive-screenshot.js https://nodejs-dersleri.github.io/ true phantomjs responsive-screenshot.js https://nodejs-dersleri.github.io/ png true
Author
Salih sagdilek salihsagdilek@gmail.com http://phantomjs.org/api/system/property/args.html
Queries and returns a list of the command-line arguments. The first one is always the script name, which is then followed by the subsequent arguments.
Referenced by ListenToMe.View.SectionListView::CoreWindow_VisibilityChanged(), getClipping(), getFileExtension(), ListenToMe.App::InitializeComponent(), ListenToMe.View.SectionDetails::navigationHelper_LoadState(), ListenToMe.ViewModel.ViewModelBase::NotifyPropertyChanged(), and ClassLibrary.model.Element::NotifyPropertyChanged().
var clipping = getClipping()
set if clipping ? {boolean}
var ext = getFileExtension()
set output extension format {*}
Referenced by getFileName().
var fs = require('fs')
http://phantomjs.org/api/fs/
file system api
Referenced by urlToDir().
var page = new WebPage()
http://phantomjs.org/api/webpage/
Web page api
var urlAddress = args[1].toLowerCase()
setup url address (second argument);
var viewports
Initial value:
= [
    {
        width : 1200,
        height : 800
    },
    {
        width : 1024,
        height : 768
    },
    {
        width : 768,
        height : 1024
    },
    {
        width : 480,
        height : 640
    },
    {
        width : 320,
        height : 480
    }
]
setup viewports