C:/Users/user/source/repos/Hoermirzu/ListenToMe-master-89f0b49594deaade7bfad24dad062ff16eca36da/packages/PhantomJS.2.1.1/tools/phantomjs/examples/stdin-stdout-stderr.js File Reference
Functions
system stdout write ('Hello, system.stdout.write!')
system stdout writeLine ('\nHello, system.stdout.writeLine!')
system stdout writeLine ('system.stdin.readLine(): ')
system stdout writeLine (JSON.stringify(line))
system stdout writeLine (JSON.stringify(input))
phantom exit (0)
Variables
use strict
var system = require('system')
var line = system.stdin.readLine()
var input = system.stdin.read(5)
Function Documentation
phantom exit (0)
system stderr write (' Hello, system.stdout.write!')
system stderr writeLine ('\ nHello, system.stdout.writeLine!')
system stdout writeLine ('system.stdin.readLine(): ')
system stdout writeLine (JSON. stringifyline)
system stdout writeLine (JSON. stringifyinput)
Variable Documentation
var input = system.stdin.read(5)
var line = system.stdin.readLine()
Referenced by WcfService1.Implementation_Mock::GetAllElements(), WcfService1.Implementation_Mock::readFile(), WcfService1.ServiceClass::ReadFile(), MockServiceImplementation::readFile(), and WcfService1.ServiceClass::ReadLinesContainingString().
use strict
var system = require('system')