C:/Users/user/source/repos/Hoermirzu/ListenToMe-master-89f0b49594deaade7bfad24dad062ff16eca36da/packages/PhantomJS.2.1.1/tools/phantomjs/examples/walk_through_frames.js File Reference
Functions
function pageTitle (page)
function setPageTitle (page, newTitle)
p open (`../test/webpage-spec-frames/index.html`, function(status){console.log(`pageTitle(): `+pageTitle(p));console.log(`currentFrameName(): `+p.currentFrameName());console.log(`childFramesCount(): `+p.childFramesCount());console.log(`childFramesName(): `+p.childFramesName());console.log(`setPageTitle(CURRENT TITLE+'-visited')`);setPageTitle(p, pageTitle(p)+`-visited`);console.log(``);console.log(`p.switchToChildFrame(\`frame1\`): `+p.switchToChildFrame(`frame1`));console.log(`pageTitle(): `+pageTitle(p));console.log(`currentFrameName(): `+p.currentFrameName());console.log(`childFramesCount(): `+p.childFramesCount());console.log(`childFramesName(): `+p.childFramesName());console.log(`setPageTitle(CURRENT TITLE+'-visited')`);setPageTitle(p, pageTitle(p)+`-visited`);console.log(``);console.log(`p.switchToChildFrame(\`frame1-2\`): `+p.switchToChildFrame(`frame1-2`));console.log(`pageTitle(): `+pageTitle(p));console.log(`currentFrameName(): `+p.currentFrameName());console.log(`childFramesCount(): `+p.childFramesCount());console.log(`childFramesName(): `+p.childFramesName());console.log(`setPageTitle(CURRENT TITLE+'-visited')`);setPageTitle(p, pageTitle(p)+`-visited`);console.log(``);console.log(`p.switchToParentFrame(): `+p.switchToParentFrame());console.log(`pageTitle(): `+pageTitle(p));console.log(`currentFrameName(): `+p.currentFrameName());console.log(`childFramesCount(): `+p.childFramesCount());console.log(`childFramesName(): `+p.childFramesName());console.log(`setPageTitle(CURRENT TITLE+'-visited')`);setPageTitle(p, pageTitle(p)+`-visited`);console.log(``);console.log(`p.switchToChildFrame(0): `+p.switchToChildFrame(0));console.log(`pageTitle(): `+pageTitle(p));console.log(`currentFrameName(): `+p.currentFrameName());console.log(`childFramesCount(): `+p.childFramesCount());console.log(`childFramesName(): `+p.childFramesName());console.log(`setPageTitle(CURRENT TITLE+'-visited')`);setPageTitle(p, pageTitle(p)+`-visited`);console.log(``);console.log(`p.switchToMainFrame()`);p.switchToMainFrame();console.log(`pageTitle(): `+pageTitle(p));console.log(`currentFrameName(): `+p.currentFrameName());console.log(`childFramesCount(): `+p.childFramesCount());console.log(`childFramesName(): `+p.childFramesName());console.log(`setPageTitle(CURRENT TITLE+'-visited')`);setPageTitle(p, pageTitle(p)+`-visited`);console.log(``);console.log(`p.switchToChildFrame(\`frame2\`): `+p.switchToChildFrame(`frame2`));console.log(`pageTitle(): `+pageTitle(p));console.log(`currentFrameName(): `+p.currentFrameName());console.log(`childFramesCount(): `+p.childFramesCount());console.log(`childFramesName(): `+p.childFramesName());console.log(`setPageTitle(CURRENT TITLE+'-visited')`);setPageTitle(p, pageTitle(p)+`-visited`);console.log(``);phantom.exit();})
Variables
use strict
var p = require(`webpage`).create()
Function Documentation
[open(""../test/webpage-spec-frames/index.html"", function(status)console.log(""pageTitle(): ""+pageTitle(p));console.log(""currentFrameName(): ""+p.currentFrameName());console.log(""childFramesCount(): ""+p.childFramesCount());console.log(""childFramesName(): ""+p.childFramesName());console.log(""setPageTitle(CURRENT TITLE+'-visited')"");setPageTitle(p, pageTitle(p)+""-visited"");console.log("""");console.log(""p.switchToChildFrame(\""frame1\""): ""+p.switchToChildFrame(""frame1""));console.log(""pageTitle(): ""+pageTitle(p));console.log(""currentFrameName(): ""+p.currentFrameName());console.log(""childFramesCount(): ""+p.childFramesCount());console.log(""childFramesName(): ""+p.childFramesName());console.log(""setPageTitle(CURRENT TITLE+'-visited')"");setPageTitle(p, pageTitle(p)+""-visited"");console.log("""");console.log(""p.switchToChildFrame(\""frame1-2\""): ""+p.switchToChildFrame(""frame1-2""));console.log(""pageTitle(): ""+pageTitle(p));console.log(""currentFrameName(): ""+p.currentFrameName());console.log(""childFramesCount(): ""+p.childFramesCount());console.log(""childFramesName(): ""+p.childFramesName());console.log(""setPageTitle(CURRENT TITLE+'-visited')"");setPageTitle(p, pageTitle(p)+""-visited"");console.log("""");console.log(""p.switchToParentFrame(): ""+p.switchToParentFrame());console.log(""pageTitle(): ""+pageTitle(p));console.log(""currentFrameName(): ""+p.currentFrameName());console.log(""childFramesCount(): ""+p.childFramesCount());console.log(""childFramesName(): ""+p.childFramesName());console.log(""setPageTitle(CURRENT TITLE+'-visited')"");setPageTitle(p, pageTitle(p)+""-visited"");console.log("""");console.log(""p.switchToChildFrame(0): ""+p.switchToChildFrame(0));console.log(""pageTitle(): ""+pageTitle(p));console.log(""currentFrameName(): ""+p.currentFrameName());console.log(""childFramesCount(): ""+p.childFramesCount());console.log(""childFramesName(): ""+p.childFramesName());console.log(""setPageTitle(CURRENT TITLE+'-visited')"");setPageTitle(p, pageTitle(p)+""-visited"");console.log("""");console.log(""p.switchToMainFrame()"");p.switchToMainFrame();console.log(""pageTitle(): ""+pageTitle(p));console.log(""currentFrameName(): ""+p.currentFrameName());console.log(""childFramesCount(): ""+p.childFramesCount());console.log(""childFramesName(): ""+p.childFramesName());console.log(""setPageTitle(CURRENT TITLE+'-visited')"");setPageTitle(p, pageTitle(p)+""-visited"");console.log("""");console.log(""p.switchToChildFrame(\""frame2\""): ""+p.switchToChildFrame(""frame2""));console.log(""pageTitle(): ""+pageTitle(p));console.log(""currentFrameName(): ""+p.currentFrameName());console.log(""childFramesCount(): ""+p.childFramesCount());console.log(""childFramesName(): ""+p.childFramesName());console.log(""setPageTitle(CURRENT TITLE+'-visited')"");setPageTitle(p, pageTitle(p)+""-visited"");console.log("""");phantom.exit();)open("../test/webpage-spec-frames/index.html", function(status){console.log("pageTitle(): "+pageTitle(p));console.log("currentFrameName(): "+p.currentFrameName());console.log("childFramesCount(): "+p.childFramesCount());console.log("childFramesName(): "+p.childFramesName());console.log("setPageTitle(CURRENT TITLE+'-visited')");setPageTitle(p, pageTitle(p)+"-visited");console.log("");console.log("p.switchToChildFrame(\"frame1\"): "+p.switchToChildFrame("frame1"));console.log("pageTitle(): "+pageTitle(p));console.log("currentFrameName(): "+p.currentFrameName());console.log("childFramesCount(): "+p.childFramesCount());console.log("childFramesName(): "+p.childFramesName());console.log("setPageTitle(CURRENT TITLE+'-visited')");setPageTitle(p, pageTitle(p)+"-visited");console.log("");console.log("p.switchToChildFrame(\"frame1-2\"): "+p.switchToChildFrame("frame1-2"));console.log("pageTitle(): "+pageTitle(p));console.log("currentFrameName(): "+p.currentFrameName());console.log("childFramesCount(): "+p.childFramesCount());console.log("childFramesName(): "+p.childFramesName());console.log("setPageTitle(CURRENT TITLE+'-visited')");setPageTitle(p, pageTitle(p)+"-visited");console.log("");console.log("p.switchToParentFrame(): "+p.switchToParentFrame());console.log("pageTitle(): "+pageTitle(p));console.log("currentFrameName(): "+p.currentFrameName());console.log("childFramesCount(): "+p.childFramesCount());console.log("childFramesName(): "+p.childFramesName());console.log("setPageTitle(CURRENT TITLE+'-visited')");setPageTitle(p, pageTitle(p)+"-visited");console.log("");console.log("p.switchToChildFrame(0): "+p.switchToChildFrame(0));console.log("pageTitle(): "+pageTitle(p));console.log("currentFrameName(): "+p.currentFrameName());console.log("childFramesCount(): "+p.childFramesCount());console.log("childFramesName(): "+p.childFramesName());console.log("setPageTitle(CURRENT TITLE+'-visited')");setPageTitle(p, pageTitle(p)+"-visited");console.log("");console.log("p.switchToMainFrame()");p.switchToMainFrame();console.log("pageTitle(): "+pageTitle(p));console.log("currentFrameName(): "+p.currentFrameName());console.log("childFramesCount(): "+p.childFramesCount());console.log("childFramesName(): "+p.childFramesName());console.log("setPageTitle(CURRENT TITLE+'-visited')");setPageTitle(p, pageTitle(p)+"-visited");console.log("");console.log("p.switchToChildFrame(\"frame2\"): "+p.switchToChildFrame("frame2"));console.log("pageTitle(): "+pageTitle(p));console.log("currentFrameName(): "+p.currentFrameName());console.log("childFramesCount(): "+p.childFramesCount());console.log("childFramesName(): "+p.childFramesName());console.log("setPageTitle(CURRENT TITLE+'-visited')");setPageTitle(p, pageTitle(p)+"-visited");console.log("");phantom.exit();})]p open (`../test/webpage-spec-frames/index.html` , [function(status){console.log(`pageTitle(): `+pageTitle(p));console.log(`currentFrameName(): `+p.currentFrameName());console.log(`childFramesCount(): `+p.childFramesCount());console.log(`childFramesName(): `+p.childFramesName());console.log(`setPageTitle(CURRENT TITLE+'-visited')`);setPageTitle(p, pageTitle(p)+`-visited`);console.log(``);console.log(`p.switchToChildFrame(\`frame1\`): `+p.switchToChildFrame(`frame1`));console.log(`pageTitle(): `+pageTitle(p));console.log(`currentFrameName(): `+p.currentFrameName());console.log(`childFramesCount(): `+p.childFramesCount());console.log(`childFramesName(): `+p.childFramesName());console.log(`setPageTitle(CURRENT TITLE+'-visited')`);setPageTitle(p, pageTitle(p)+`-visited`);console.log(``);console.log(`p.switchToChildFrame(\`frame1-2\`): `+p.switchToChildFrame(`frame1-2`));console.log(`pageTitle(): `+pageTitle(p));console.log(`currentFrameName(): `+p.currentFrameName());console.log(`childFramesCount(): `+p.childFramesCount());console.log(`childFramesName(): `+p.childFramesName());console.log(`setPageTitle(CURRENT TITLE+'-visited')`);setPageTitle(p, pageTitle(p)+`-visited`);console.log(``);console.log(`p.switchToParentFrame(): `+p.switchToParentFrame());console.log(`pageTitle(): `+pageTitle(p));console.log(`currentFrameName(): `+p.currentFrameName());console.log(`childFramesCount(): `+p.childFramesCount());console.log(`childFramesName(): `+p.childFramesName());console.log(`setPageTitle(CURRENT TITLE+'-visited')`);setPageTitle(p, pageTitle(p)+`-visited`);console.log(``);console.log(`p.switchToChildFrame(0): `+p.switchToChildFrame(0));console.log(`pageTitle(): `+pageTitle(p));console.log(`currentFrameName(): `+p.currentFrameName());console.log(`childFramesCount(): `+p.childFramesCount());console.log(`childFramesName(): `+p.childFramesName());console.log(`setPageTitle(CURRENT TITLE+'-visited')`);setPageTitle(p, pageTitle(p)+`-visited`);console.log(``);console.log(`p.switchToMainFrame()`);p.switchToMainFrame();console.log(`pageTitle(): `+pageTitle(p));console.log(`currentFrameName(): `+p.currentFrameName());console.log(`childFramesCount(): `+p.childFramesCount());console.log(`childFramesName(): `+p.childFramesName());console.log(`setPageTitle(CURRENT TITLE+'-visited')`);setPageTitle(p, pageTitle(p)+`-visited`);console.log(``);console.log(`p.switchToChildFrame(\`frame2\`): `+p.switchToChildFrame(`frame2`));console.log(`pageTitle(): `+pageTitle(p));console.log(`currentFrameName(): `+p.currentFrameName());console.log(`childFramesCount(): `+p.childFramesCount());console.log(`childFramesName(): `+p.childFramesName());console.log(`setPageTitle(CURRENT TITLE+'-visited')`);setPageTitle(p, pageTitle(p)+`-visited`);console.log(``);phantom.exit();}])
function pageTitle (page)
References page.
Referenced by ListenToMe.View.SectionListView::Connect(), and setPageTitle().
function setPageTitle (page, newTitle)
References p, page, and pageTitle().
Variable Documentation
var p = require(`webpage`).create()
Referenced by setPageTitle().
use strict