//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuisBot.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LuisBot_Resource_Resource1_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LuisBot_Resource_Resource1_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LuisBot.Resource.LuisBot_Resource_Resource1_en", typeof(LuisBot_Resource_Resource1_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form was sucessfully filled in..
        /// </summary>
        internal static string AfterOrder {
            get {
                return ResourceManager.GetString("AfterOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for contacting our support team. Your ticket number is {ticketNumber}..
        /// </summary>
        internal static string AfterSupport {
            get {
                return ResourceManager.GetString("AfterSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your.
        /// </summary>
        internal static string AskForFieldFemale {
            get {
                return ResourceManager.GetString("AskForFieldFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is your.
        /// </summary>
        internal static string AskForFieldMaleNeutral {
            get {
                return ResourceManager.GetString("AskForFieldMaleNeutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the following:.
        /// </summary>
        internal static string AskForSave {
            get {
                return ResourceManager.GetString("AskForSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you looking for a form or something else?.
        /// </summary>
        internal static string AskSelectDialog {
            get {
                return ResourceManager.GetString("AskSelectDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you are at lat/lon.
        /// </summary>
        internal static string coordinates {
            get {
                return ResourceManager.GetString("coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooops, what you wrote is not a valid option, please try again.
        /// </summary>
        internal static string DialogRetry {
            get {
                return ResourceManager.GetString("DialogRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed with message: {ex.Message}.
        /// </summary>
        internal static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the fillin Intent intent. You said:.
        /// </summary>
        internal static string FillInMessage {
            get {
                return ResourceManager.GetString("FillInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome at ESF_2 Form!.
        /// </summary>
        internal static string FormWelcomeMessage {
            get {
                return ResourceManager.GetString("FormWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the goBack intent..
        /// </summary>
        internal static string GoBackMessage {
            get {
                return ResourceManager.GetString("GoBackMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has this solved your problem?.
        /// </summary>
        internal static string GotHelpedQuestion {
            get {
                return ResourceManager.GetString("GotHelpedQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am your asistant at filling out forms. Try &quot;open section &lt;section number&gt;&quot; for navigation between sections. or say go next/go back.
        /// </summary>
        internal static string GreetingMessage {
            get {
                return ResourceManager.GetString("GreetingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hello.
        /// </summary>
        internal static string hello {
            get {
                return ResourceManager.GetString("hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What can I do for you?.
        /// </summary>
        internal static string HelpClarification {
            get {
                return ResourceManager.GetString("HelpClarification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At Help.
        /// </summary>
        internal static string HelpSpeak {
            get {
                return ResourceManager.GetString("HelpSpeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am pleased to help you out..
        /// </summary>
        internal static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can converse on:.
        /// </summary>
        internal static string HelpTitel {
            get {
                return ResourceManager.GetString("HelpTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome at help dialog. This Bot is aiding you at filling in a form. Try utterances like &apos;My company is innobis&apos; to get started..
        /// </summary>
        internal static string HelpWelcomeMessage {
            get {
                return ResourceManager.GetString("HelpWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hi.
        /// </summary>
        internal static string hi {
            get {
                return ResourceManager.GetString("hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LuisBot.JsonDummyForBot_EN.json.
        /// </summary>
        internal static string JsonFile {
            get {
                return ResourceManager.GetString("JsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I recognized no intent behing your query: .
        /// </summary>
        internal static string LuisNone {
            get {
                return ResourceManager.GetString("LuisNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the none intent..
        /// </summary>
        internal static string NoneMessage {
            get {
                return ResourceManager.GetString("NoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        internal static string OptionForm {
            get {
                return ResourceManager.GetString("OptionForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string OptionHelp {
            get {
                return ResourceManager.GetString("OptionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determine Intent.
        /// </summary>
        internal static string OptionLuis {
            get {
                return ResourceManager.GetString("OptionLuis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Pictures.
        /// </summary>
        internal static string OptionUpload {
            get {
                return ResourceManager.GetString("OptionUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to problem.
        /// </summary>
        internal static string problem {
            get {
                return ResourceManager.GetString("problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your data has been processed.
        /// </summary>
        internal static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey.
        /// </summary>
        internal static string regionalGreeting {
            get {
                return ResourceManager.GetString("regionalGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shall I save this input?.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved..
        /// </summary>
        internal static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You stopped at {e.Last}. Next time you can continue from there..
        /// </summary>
        internal static string StopUnexpected {
            get {
                return ResourceManager.GetString("StopUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support.
        /// </summary>
        internal static string support {
            get {
                return ResourceManager.GetString("support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooops! Too many attemps :(. But don&apos;t worry, I&apos;m handling that exception and you can try again!.
        /// </summary>
        internal static string TooManyAttempts {
            get {
                return ResourceManager.GetString("TooManyAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That should not have happend. You could try at a later time..
        /// </summary>
        internal static string TryLater {
            get {
                return ResourceManager.GetString("TryLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (1) Show inline attachment.
        /// </summary>
        internal static string UploadDialogOptionInline {
            get {
                return ResourceManager.GetString("UploadDialogOptionInline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (2) Show uploaded attachment.
        /// </summary>
        internal static string UploadDialogOptionService {
            get {
                return ResourceManager.GetString("UploadDialogOptionService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (3) Show Internet attachment.
        /// </summary>
        internal static string UploadDialogOptionWeb {
            get {
                return ResourceManager.GetString("UploadDialogOptionWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What sample option would you like to see?.
        /// </summary>
        internal static string UploadDialogPrompt {
            get {
                return ResourceManager.GetString("UploadDialogPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome, here you can see attachment alternatives:.
        /// </summary>
        internal static string UploadDialogWelcome {
            get {
                return ResourceManager.GetString("UploadDialogWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome, here you can see attachment alternatives:.
        /// </summary>
        internal static string UploadOptions {
            get {
                return ResourceManager.GetString("UploadOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
