//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuisBot.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LuisBot.Resource.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formular ausgefüllt.
        /// </summary>
        internal static string AfterOrder {
            get {
                return ResourceManager.GetString("AfterOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danke für die Support-Kontaktaufnahme. Deine Ticketnummer ist {ticketNumber}.&quot;);.
        /// </summary>
        internal static string AfterSupport {
            get {
                return ResourceManager.GetString("AfterSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was ist deine.
        /// </summary>
        internal static string AskForFieldFemale {
            get {
                return ResourceManager.GetString("AskForFieldFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was ist dein.
        /// </summary>
        internal static string AskForFieldMaleNeutral {
            get {
                return ResourceManager.GetString("AskForFieldMaleNeutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchtest du folgendes speichern:.
        /// </summary>
        internal static string AskForSave {
            get {
                return ResourceManager.GetString("AskForSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suchst du ein Formular oder etwas anderes?.
        /// </summary>
        internal static string AskSelectDialog {
            get {
                return ResourceManager.GetString("AskSelectDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Unternehmensangaben-Intention wurde erreicht.
        /// </summary>
        internal static string CompanyDetailsMessage {
            get {
                return ResourceManager.GetString("CompanyDetailsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du bist bei Breitengrad/Längengrad:.
        /// </summary>
        internal static string coordinates {
            get {
                return ResourceManager.GetString("coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Antwort verstehe ich nicht. Versuch es erneut, bitte..
        /// </summary>
        internal static string DialogRetry {
            get {
                return ResourceManager.GetString("DialogRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausnahme aufgetreten:.
        /// </summary>
        internal static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde eine Feld-Ausfüll-Intention erkannt. Du sagtest:.
        /// </summary>
        internal static string FillInMessage {
            get {
                return ResourceManager.GetString("FillInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willkommen im ESF_2 Bot!.
        /// </summary>
        internal static string FormWelcomeMessage {
            get {
                return ResourceManager.GetString("FormWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Zurückgehen-Intention wurde erreicht..
        /// </summary>
        internal static string GoBackMessage {
            get {
                return ResourceManager.GetString("GoBackMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hat das geholfen?.
        /// </summary>
        internal static string GotHelpedQuestion {
            get {
                return ResourceManager.GetString("GotHelpedQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ich bin dein Assistent beim Ausfüllen von Formularen. Versuche einmal &apos;Ich möchte die Unternehmensangaben im ESF_2 Formular ausfüllen&apos;..
        /// </summary>
        internal static string GreetingMessage {
            get {
                return ResourceManager.GetString("GreetingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hallo.
        /// </summary>
        internal static string hello {
            get {
                return ResourceManager.GetString("hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hilfe.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was kann ich für dich tun?.
        /// </summary>
        internal static string HelpClarification {
            get {
                return ResourceManager.GetString("HelpClarification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In der Hilfe..
        /// </summary>
        internal static string HelpSpeak {
            get {
                return ResourceManager.GetString("HelpSpeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klar helfe ich dir..
        /// </summary>
        internal static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie können folgende Dialoge mit mir führen:.
        /// </summary>
        internal static string HelpTitel {
            get {
                return ResourceManager.GetString("HelpTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Willkommen in der Hilfe. Dieser Bot ist dazu da Formularangaben zu machen. Versuchen Sie &apos;Meine Firma ist innobis&apos; um das Feld Firma zu füllen..
        /// </summary>
        internal static string HelpWelcomeMessage {
            get {
                return ResourceManager.GetString("HelpWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hi.
        /// </summary>
        internal static string hi {
            get {
                return ResourceManager.GetString("hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LuisBot.JsonDummyForBot_DE.json.
        /// </summary>
        internal static string JsonFile {
            get {
                return ResourceManager.GetString("JsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ich habe keine Intention hinter dieser Anfrage erkannt: .
        /// </summary>
        internal static string LuisNone {
            get {
                return ResourceManager.GetString("LuisNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nein.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurde keine spezielle Intention erkannt. Du sagtest:.
        /// </summary>
        internal static string NoneMessage {
            get {
                return ResourceManager.GetString("NoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formular.
        /// </summary>
        internal static string OptionForm {
            get {
                return ResourceManager.GetString("OptionForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hilfe.
        /// </summary>
        internal static string OptionHelp {
            get {
                return ResourceManager.GetString("OptionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprachintentions-Erkennung.
        /// </summary>
        internal static string OptionLuis {
            get {
                return ResourceManager.GetString("OptionLuis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeige Bilder.
        /// </summary>
        internal static string OptionUpload {
            get {
                return ResourceManager.GetString("OptionUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem.
        /// </summary>
        internal static string problem {
            get {
                return ResourceManager.GetString("problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deine Werte werden verarbeitet..
        /// </summary>
        internal static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moin.
        /// </summary>
        internal static string regionalGreeting {
            get {
                return ResourceManager.GetString("regionalGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soll ich diese Werte speichern?.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gespeichert..
        /// </summary>
        internal static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du hast aufgehört. Nächstes Mal kannst du weiterarbeiten bei: .
        /// </summary>
        internal static string StopUnexpected {
            get {
                return ResourceManager.GetString("StopUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string support {
            get {
                return ResourceManager.GetString("support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danke..
        /// </summary>
        internal static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh-oh. zu viele Versuche :(. Aber keine Sorge, ich kümmere mich um diesen Zusatnd und du kannst es erneut probieren..
        /// </summary>
        internal static string TooManyAttempts {
            get {
                return ResourceManager.GetString("TooManyAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entschuldigung, ich bin begriffsstutzig. Versuch es später noch mal..
        /// </summary>
        internal static string TryLater {
            get {
                return ResourceManager.GetString("TryLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (1) Inine-Foto zeigen.
        /// </summary>
        internal static string UploadDialogOptionInline {
            get {
                return ResourceManager.GetString("UploadDialogOptionInline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (2) Service Foto zeigen.
        /// </summary>
        internal static string UploadDialogOptionService {
            get {
                return ResourceManager.GetString("UploadDialogOptionService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (3) Internet Foto.
        /// </summary>
        internal static string UploadDialogOptionWeb {
            get {
                return ResourceManager.GetString("UploadDialogOptionWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welche Fortoart würdest du gerne sehen?.
        /// </summary>
        internal static string UploadDialogPrompt {
            get {
                return ResourceManager.GetString("UploadDialogPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier kannst du deinene Foto Optionen wählen.
        /// </summary>
        internal static string UploadDialogWelcome {
            get {
                return ResourceManager.GetString("UploadDialogWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploadoptionen.
        /// </summary>
        internal static string UploadOptions {
            get {
                return ResourceManager.GetString("UploadOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ja.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
