//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuisBot.Resource {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LuisBot.Resource.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Formular ausgefüllt ähnelt.
        /// </summary>
        internal static string AfterOrder {
            get {
                return ResourceManager.GetString("AfterOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Danke für die Support-Kontaktaufnahme. Deine Ticketnummer ist {ticketNumber}.&quot;); ähnelt.
        /// </summary>
        internal static string AfterSupport {
            get {
                return ResourceManager.GetString("AfterSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Was ist deine ähnelt.
        /// </summary>
        internal static string AskForFieldFemale {
            get {
                return ResourceManager.GetString("AskForFieldFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Was ist dein ähnelt.
        /// </summary>
        internal static string AskForFieldMaleNeutral {
            get {
                return ResourceManager.GetString("AskForFieldMaleNeutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Möchtest du folgendes speichern: ähnelt.
        /// </summary>
        internal static string AskForSave {
            get {
                return ResourceManager.GetString("AskForSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suchst du ein Formular oder etwas anderes? ähnelt.
        /// </summary>
        internal static string AskSelectDialog {
            get {
                return ResourceManager.GetString("AskSelectDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zurück ähnelt.
        /// </summary>
        internal static string CommandBack {
            get {
                return ResourceManager.GetString("CommandBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zurück: Kehre zur vorherigen Frage zurück ähnelt.
        /// </summary>
        internal static string CommandBackHelp {
            get {
                return ResourceManager.GetString("CommandBackHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die zurück; vorherige ähnelt.
        /// </summary>
        internal static string CommandBackTerms {
            get {
                return ResourceManager.GetString("CommandBackTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hilfe ähnelt.
        /// </summary>
        internal static string CommandHelp {
            get {
                return ResourceManager.GetString("CommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hilfe: Zeige eine Übersicht der möglichen Kommandos ähnelt.
        /// </summary>
        internal static string CommandHelpHelp {
            get {
                return ResourceManager.GetString("CommandHelpHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hilfe; hilf mir; was kann ich sagen?; gottverdammt ähnelt.
        /// </summary>
        internal static string CommandHelpTerms {
            get {
                return ResourceManager.GetString("CommandHelpTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop ähnelt.
        /// </summary>
        internal static string CommandQuit {
            get {
                return ResourceManager.GetString("CommandQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop: Den Formulardialog ohne Ergebnis beenden ähnelt.
        /// </summary>
        internal static string CommandQuitHelp {
            get {
                return ResourceManager.GetString("CommandQuitHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die stop; halt; abbrechen; verlassen ähnelt.
        /// </summary>
        internal static string CommandQuitTerms {
            get {
                return ResourceManager.GetString("CommandQuitTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zurücksetzen ähnelt.
        /// </summary>
        internal static string CommandReset {
            get {
                return ResourceManager.GetString("CommandReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset: Diese Fragen erneut beginnen (ggf. mit vorherigen Default-Werten) ähnelt.
        /// </summary>
        internal static string CommandResetHelp {
            get {
                return ResourceManager.GetString("CommandResetHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die reset; zurücksetzen; rückgängig; von vorne, neu ähnelt.
        /// </summary>
        internal static string CommandResetTerms {
            get {
                return ResourceManager.GetString("CommandResetTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status ähnelt.
        /// </summary>
        internal static string CommandStatus {
            get {
                return ResourceManager.GetString("CommandStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status: Zeigt den Status der aktuellen Conversation ähnelt.
        /// </summary>
        internal static string CommandStatusHelp {
            get {
                return ResourceManager.GetString("CommandStatusHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die status; stand; information; ergebnisse; info ähnelt.
        /// </summary>
        internal static string CommandStatusTerms {
            get {
                return ResourceManager.GetString("CommandStatusTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Unternehmensangaben-Intention wurde erreicht ähnelt.
        /// </summary>
        internal static string CompanyDetailsMessage {
            get {
                return ResourceManager.GetString("CompanyDetailsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bestätigung ähnelt.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du bist bei Breitengrad/Längengrad: ähnelt.
        /// </summary>
        internal static string coordinates {
            get {
                return ResourceManager.GetString("coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Diese Antwort verstehe ich nicht. Versuch es erneut, bitte. ähnelt.
        /// </summary>
        internal static string DialogRetry {
            get {
                return ResourceManager.GetString("DialogRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ausnahme aufgetreten: ähnelt.
        /// </summary>
        internal static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wurde eine Feld-Ausfüll-Intention erkannt. Du sagtest: ähnelt.
        /// </summary>
        internal static string FillInMessage {
            get {
                return ResourceManager.GetString("FillInMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willkommen. Ich bin dein Helfer um das ESF Formular auszufüllen. Ich werde dir eine Reihe von Fragen und dich auffordern, Dokumente hochzuladen. Wenn ich etwas nicht verstehe, sei mir nicht böse, denn ich lerne kontinuierlich hinzu. Tippe einmal &quot;help&quot; ein dann sage ich dir, welche Kommandos ich bereits kenne. ähnelt.
        /// </summary>
        internal static string FormWelcomeMessage {
            get {
                return ResourceManager.GetString("FormWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Zurückgehen-Intention wurde erreicht. ähnelt.
        /// </summary>
        internal static string GoBackMessage {
            get {
                return ResourceManager.GetString("GoBackMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hat das geholfen? ähnelt.
        /// </summary>
        internal static string GotHelpedQuestion {
            get {
                return ResourceManager.GetString("GotHelpedQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ich bin dein Assistent beim Ausfüllen von Formularen. Versuche einmal &apos;Ich möchte die Unternehmensangaben im ESF_2 Formular ausfüllen&apos;. ähnelt.
        /// </summary>
        internal static string GreetingMessage {
            get {
                return ResourceManager.GetString("GreetingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hallo ähnelt.
        /// </summary>
        internal static string hello {
            get {
                return ResourceManager.GetString("hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hilfe ähnelt.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Was kann ich für dich tun? ähnelt.
        /// </summary>
        internal static string HelpClarification {
            get {
                return ResourceManager.GetString("HelpClarification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In der Hilfe. ähnelt.
        /// </summary>
        internal static string HelpSpeak {
            get {
                return ResourceManager.GetString("HelpSpeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Klar helfe ich dir. ähnelt.
        /// </summary>
        internal static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sie können folgende Dialoge mit mir führen: ähnelt.
        /// </summary>
        internal static string HelpTitel {
            get {
                return ResourceManager.GetString("HelpTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willkommen in der Hilfe. Dieser Bot ist dazu da Formularangaben zu machen. Versuchen Sie &apos;Meine Firma ist innobis&apos; um das Feld Firma zu füllen. ähnelt.
        /// </summary>
        internal static string HelpWelcomeMessage {
            get {
                return ResourceManager.GetString("HelpWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die hi ähnelt.
        /// </summary>
        internal static string hi {
            get {
                return ResourceManager.GetString("hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LuisBot.JsonDummyForBot_DE.json ähnelt.
        /// </summary>
        internal static string JsonFile {
            get {
                return ResourceManager.GetString("JsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ich habe keine Intention hinter dieser Anfrage erkannt:  ähnelt.
        /// </summary>
        internal static string LuisNone {
            get {
                return ResourceManager.GetString("LuisNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nein; nö; nee; na; 2 ähnelt.
        /// </summary>
        internal static string MatchNo {
            get {
                return ResourceManager.GetString("MatchNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ja, ja; stimmt; richtig; ok ähnelt.
        /// </summary>
        internal static string MatchYes {
            get {
                return ResourceManager.GetString("MatchYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die nein ähnelt.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wurde keine spezielle Intention erkannt. Du sagtest: ähnelt.
        /// </summary>
        internal static string NoneMessage {
            get {
                return ResourceManager.GetString("NoneMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Formular ähnelt.
        /// </summary>
        internal static string OptionForm {
            get {
                return ResourceManager.GetString("OptionForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hilfe ähnelt.
        /// </summary>
        internal static string OptionHelp {
            get {
                return ResourceManager.GetString("OptionHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprachintentions-Erkennung ähnelt.
        /// </summary>
        internal static string OptionLuis {
            get {
                return ResourceManager.GetString("OptionLuis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeige Bilder ähnelt.
        /// </summary>
        internal static string OptionUpload {
            get {
                return ResourceManager.GetString("OptionUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Problem ähnelt.
        /// </summary>
        internal static string problem {
            get {
                return ResourceManager.GetString("problem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deine Werte werden verarbeitet. ähnelt.
        /// </summary>
        internal static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ich gehe zurück zum Einstiegsdialog ähnelt.
        /// </summary>
        internal static string ReEnterRoot {
            get {
                return ResourceManager.GetString("ReEnterRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die moin ähnelt.
        /// </summary>
        internal static string regionalGreeting {
            get {
                return ResourceManager.GetString("regionalGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soll ich diese Werte speichern? ähnelt.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gespeichert. ähnelt.
        /// </summary>
        internal static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du hast aufgehört. Nächstes Mal kannst du weiterarbeiten bei:  ähnelt.
        /// </summary>
        internal static string StopUnexpected {
            get {
                return ResourceManager.GetString("StopUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Information ähnelt.
        /// </summary>
        internal static string support {
            get {
                return ResourceManager.GetString("support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ist dies Ihre Auswahl? ähnelt.
        /// </summary>
        internal static string TemplateConfirmation {
            get {
                return ResourceManager.GetString("TemplateConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Danke. ähnelt.
        /// </summary>
        internal static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Oh-oh. zu viele Versuche :(. Aber keine Sorge, ich kümmere mich um diesen Zusatnd und du kannst es erneut probieren. ähnelt.
        /// </summary>
        internal static string TooManyAttempts {
            get {
                return ResourceManager.GetString("TooManyAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entschuldigung, ich bin begriffsstutzig. Versuch es später noch mal. ähnelt.
        /// </summary>
        internal static string TryLater {
            get {
                return ResourceManager.GetString("TryLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte wähle die Datei aus, die du hochladen möchtest. ähnelt.
        /// </summary>
        internal static string UploadAttachment {
            get {
                return ResourceManager.GetString("UploadAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hier ein Bild des Bots ähnelt.
        /// </summary>
        internal static string UploadBot {
            get {
                return ResourceManager.GetString("UploadBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (1) Inine-Foto zeigen ähnelt.
        /// </summary>
        internal static string UploadDialogOptionInline {
            get {
                return ResourceManager.GetString("UploadDialogOptionInline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (2) Service Foto zeigen ähnelt.
        /// </summary>
        internal static string UploadDialogOptionService {
            get {
                return ResourceManager.GetString("UploadDialogOptionService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (3) Internet Foto ähnelt.
        /// </summary>
        internal static string UploadDialogOptionWeb {
            get {
                return ResourceManager.GetString("UploadDialogOptionWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welche Fortoart würdest du gerne sehen? ähnelt.
        /// </summary>
        internal static string UploadDialogPrompt {
            get {
                return ResourceManager.GetString("UploadDialogPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hier kannst du deinene Foto Optionen wählen ähnelt.
        /// </summary>
        internal static string UploadDialogWelcome {
            get {
                return ResourceManager.GetString("UploadDialogWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hier ein Bild aus dem Internet ähnelt.
        /// </summary>
        internal static string UploadInternet {
            get {
                return ResourceManager.GetString("UploadInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hallo. Eigentlich sollte hier ein Anhang angehängt werden aber kein geeigneter wurde ausgewählt. Bitte versuche noch einmal eine Nachricht mit Anhang zu senden ähnelt.
        /// </summary>
        internal static string UploadNoAttachment {
            get {
                return ResourceManager.GetString("UploadNoAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uploadoptionen ähnelt.
        /// </summary>
        internal static string UploadOptions {
            get {
                return ResourceManager.GetString("UploadOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ja ähnelt.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
